name: Actions Cleanup

on:
  schedule:
    # Runs at 00:00 every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch: # Allows manual trigger

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraiano/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2 # Keeps only the last 2 days of logs
          keep_minimum_runs: 3 # Always keeps at least the last 3 runs