name: TeleHub Push Notifier

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python send.py

      - name: Commit & push out folder
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add out
          git commit -m "Update out directory" || echo "No changes to commit"
          git push