name: TeleHub Push Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *" # Runs every day at 3 AM UTC"

jobs:
  notify:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python send.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit & push updated scope files
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add res out
          git commit -m "Auto Update scopes & merged targets" || echo "No changes"
          git push
