name: Wildcard Subfinder Incremental

on:
  workflow_dispatch:

jobs:
  recon:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Subfinder
        run: |
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Send notfication to Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d '{"chat_id": "'${{ secrets.CHAT_ID }}'", "text": "Starting incremental subfinder scan..."}' -o /dev/null

      - name: Prepare Directories
        run: |
          mkdir -p out/state log
          touch out/state/processed_roots.txt
          touch out/subdomains.txt

      - name: Prepare Root Domains
        run: |
          cat out/bbp/domains.txt | sort -u > out/state/current_roots.txt

      - name: Find New Roots
        run: |
          comm -23 out/state/current_roots.txt out/state/processed_roots.txt > out/state/new_roots.txt

      - name: Select Batch (10 Domains)
        run: |
          head -n 10 out/state/new_roots.txt > out/state/batch.txt
          echo "Batch domains:"
          cat out/state/batch.txt || true

      - name: Run Subfinder On Batch
        run: |
          if [ -s out/state/batch.txt ]; then
            subfinder -dL out/state/batch.txt -all -recursive -silent \
            | sort -u >> out/subdomains.txt

            cat out/state/batch.txt >> out/state/processed_roots.txt
            sort -u out/state/processed_roots.txt -o out/state/processed_roots.txt
          else
            echo "No new domains to scan."
          fi
          
      - name: Commit Results
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git add out/subdomains.txt out/state/processed_roots.txt
          git commit -m "Incremental update: $(date +'%Y-%m-%d')" || echo "No changes"
          git push